// Exam-style "yield" tiers for every entry. A curated set of high-yield,
// medium-yield, and demigod (ultra-obscure trivia) slugs per section; anything
// not listed defaults to "Good to know". Kept dependency-free of sections.ts
// to avoid a circular import (section is passed in as a plain string).

export const TIERS_ORDER = [
  "High yield",
  "Medium yield",
  "Good to know",
  "Demigod",
] as const;
export type Tier = (typeof TIERS_ORDER)[number];

export const TIER_META: Record<
  Tier,
  { emoji: string; short: string; className: string }
> = {
  "High yield": {
    emoji: "🔥",
    short: "High",
    className:
      "border-rose-500/40 bg-rose-500/15 text-rose-700 dark:border-rose-400/40 dark:bg-rose-400/15 dark:text-rose-300",
  },
  "Medium yield": {
    emoji: "⭐",
    short: "Med",
    className:
      "border-amber-500/40 bg-amber-500/15 text-amber-700 dark:border-amber-400/40 dark:bg-amber-400/15 dark:text-amber-300",
  },
  "Good to know": {
    emoji: "📘",
    short: "Good",
    className:
      "border-glass-border bg-glass text-muted",
  },
  Demigod: {
    emoji: "👑",
    short: "Demigod",
    className:
      "border-fuchsia-500/40 bg-fuchsia-500/15 text-fuchsia-700 dark:border-fuchsia-400/40 dark:bg-fuchsia-400/15 dark:text-fuchsia-300",
  },
};

type TierSet = { high: string[]; medium: string[]; demigod: string[] };

const TIERS: Record<string, TierSet> = {
  bacteria: {
    high: [
      "staphylococcus-aureus",
      "streptococcus-pyogenes",
      "streptococcus-pneumoniae",
      "escherichia-coli",
      "mycobacterium-tuberculosis",
      "neisseria-gonorrhoeae",
      "neisseria-meningitidis",
      "pseudomonas-aeruginosa",
      "klebsiella-pneumoniae",
      "clostridioides-difficile",
      "clostridium-botulinum",
      "clostridium-tetani",
      "helicobacter-pylori",
      "treponema-pallidum",
      "borrelia-burgdorferi",
      "salmonella-enterica",
      "shigella-dysenteriae",
      "vibrio-cholerae",
      "haemophilus-influenzae",
      "listeria-monocytogenes",
      "bacillus-anthracis",
      "corynebacterium-diphtheriae",
      "enterococcus-faecalis",
      "campylobacter-jejuni",
      "chlamydia-trachomatis",
      "mycoplasma-pneumoniae",
      "staphylococcus-epidermidis",
      "streptococcus-agalactiae",
    ],
    medium: [
      "bordetella-pertussis",
      "legionella-pneumophila",
      "bacteroides-fragilis",
      "proteus-mirabilis",
      "yersinia-pestis",
      "francisella-tularensis",
      "brucella-melitensis",
      "rickettsia-rickettsii",
      "coxiella-burnetii",
      "bartonella-henselae",
      "mycobacterium-leprae",
      "mycobacterium-avium",
      "acinetobacter-baumannii",
      "serratia-marcescens",
      "enterobacter-cloacae",
      "moraxella-catarrhalis",
      "gardnerella-vaginalis",
      "actinomyces-israelii",
      "nocardia-asteroides",
      "clostridium-perfringens",
      "bacillus-cereus",
      "leptospira-interrogans",
      "streptococcus-mutans",
      "enterococcus-faecium",
      "ureaplasma-urealyticum",
      "vibrio-vulnificus",
      "vibrio-parahaemolyticus",
      "pasteurella-multocida",
      "ehrlichia-chaffeensis",
      "anaplasma-phagocytophilum",
      "rickettsia-prowazekii",
      "orientia-tsutsugamushi",
      "fusobacterium-nucleatum",
      "citrobacter-freundii",
      "mycobacterium-abscessus",
    ],
    demigod: [
      "spirillum-minus",
      "streptobacillus-moniliformis",
      "tropheryma-whipplei",
      "wolbachia-pipientis",
      "elizabethkingia-meningoseptica",
      "chromobacterium-violaceum",
      "cardiobacterium-valvarum",
      "kingella-denitrificans",
      "kingella-oralis",
      "pandoraea-apista",
      "cupriavidus-pauculus",
      "ralstonia-pickettii",
      "chryseobacterium-indologenes",
      "grimontia-hollisae",
      "shewanella-putrefaciens",
      "bilophila-wadsworthia",
      "leptotrichia-buccalis",
      "selenomonas-ruminantium",
      "ornithobacterium-rhinotracheale",
      "kocuria-rosea",
      "kytococcus-sedentarius",
      "dermabacter-hominis",
      "microbacterium-paraoxydans",
      "paenibacillus-larvae",
      "brevibacterium-casei",
      "abiotrophia-defectiva",
      "weissella-confusa",
      "atopobium-vaginae",
      "mobiluncus-curtisii",
      "helicobacter-cinaedi",
      "listeria-ivanovii",
      "stomatococcus-mucilaginosus",
      "trueperella-pyogenes",
      "eggerthella-lenta",
      "cutibacterium-avidum",
      "corynebacterium-urealyticum",
      "rothia-dentocariosa",
    ],
  },
  viruses: {
    high: [
      "hiv-1",
      "influenza-a-virus",
      "sars-cov-2",
      "hepatitis-b-virus",
      "hepatitis-c-virus",
      "herpes-simplex-virus-1",
      "herpes-simplex-virus-2",
      "varicella-zoster-virus",
      "epstein-barr-virus",
      "cytomegalovirus",
      "human-papillomavirus",
      "rotavirus",
      "norovirus",
      "measles-virus",
      "rabies-virus",
      "dengue-virus",
      "ebola-virus",
      "hepatitis-a-virus",
      "respiratory-syncytial-virus",
      "mumps-virus",
      "rubella-virus",
      "poliovirus",
    ],
    medium: [
      "zika-virus",
      "west-nile-virus",
      "yellow-fever-virus",
      "mers-cov",
      "sars-cov",
      "parvovirus-b19",
      "jc-polyomavirus",
      "bk-polyomavirus",
      "monkeypox-virus",
      "variola-virus",
      "lassa-virus",
      "marburg-virus",
      "sin-nombre-hantavirus",
      "chikungunya-virus",
      "japanese-encephalitis-virus",
      "hepatitis-e-virus",
      "hepatitis-d-virus",
      "coxsackievirus-a",
      "coxsackievirus-b",
      "rhinovirus",
      "human-metapneumovirus",
      "parainfluenza-virus",
      "nipah-virus",
      "htlv-1",
      "adenovirus",
      "kaposi-sarcoma-herpesvirus",
      "human-herpesvirus-6",
      "enterovirus-71",
      "crimean-congo-hemorrhagic-fever-virus",
      "influenza-b-virus",
      "hiv-2",
    ],
    demigod: [
      "lloviu-virus",
      "menglavirus",
      "banna-virus",
      "salivirus",
      "cosavirus",
      "rosavirus",
      "aichi-virus",
      "saffold-virus",
      "ljungan-virus",
      "thogoto-virus",
      "menangle-virus",
      "usutu-virus",
      "wesselsbron-virus",
      "ilheus-virus",
      "semliki-forest-virus",
      "simian-foamy-virus",
      "cedar-henipavirus",
      "borna-disease-virus",
      "torque-teno-virus",
      "ki-polyomavirus",
      "wu-polyomavirus",
      "trichodysplasia-spinulosa-polyomavirus",
      "tanapox-virus",
      "pseudocowpox-virus",
      "buffalopox-virus",
      "yaba-monkey-tumor-virus",
      "saimiriine-herpesvirus-2",
      "lymphocryptovirus-papio",
      "herpes-b-virus",
      "gb-virus-c",
      "human-pegivirus-2",
      "hepatitis-g-virus",
      "asfarvirus-african-swine-fever",
      "circovirus-pcv2",
      "human-cyclovirus",
      "human-anellovirus",
      "snowshoe-hare-virus",
      "bunyamwera-virus",
      "akabane-virus",
      "schmallenberg-virus",
      "kemerovo-virus",
      "rio-mamore-virus",
      "monongahela-virus",
      "saint-louis-aichivirus-b",
      "lake-victoria-marburgvirus-ravn",
    ],
  },
  fungi: {
    high: [
      "candida-albicans",
      "cryptococcus-neoformans",
      "aspergillus-fumigatus",
      "histoplasma-capsulatum",
      "blastomyces-dermatitidis",
      "coccidioides-immitis",
      "pneumocystis-jirovecii",
      "candida-auris",
      "rhizopus-arrhizus",
      "sporothrix-schenckii",
      "malassezia-furfur",
      "trichophyton-rubrum",
    ],
    medium: [
      "candida-glabrata",
      "candida-krusei",
      "candida-tropicalis",
      "candida-parapsilosis",
      "cryptococcus-gattii",
      "aspergillus-flavus",
      "aspergillus-niger",
      "mucor-circinelloides",
      "paracoccidioides-brasiliensis",
      "talaromyces-marneffei",
      "fusarium-solani",
      "microsporum-canis",
      "epidermophyton-floccosum",
      "trichophyton-tonsurans",
      "trichophyton-mentagrophytes",
      "scedosporium-apiospermum",
      "exophiala-dermatitidis",
      "fonsecaea-pedrosoi",
      "madurella-mycetomatis",
      "lichtheimia-corymbifera",
    ],
    demigod: [
      "rhinosporidium-seeberi",
      "lacazia-loboi",
      "lacazia-loboi-marine",
      "lacazia-loboi-cetacean",
      "emmonsia-parva",
      "cokeromyces-recurvatus",
      "ochroconis-gallopava",
      "verruconis-gallopava",
      "rhinocladiella-mackenziei",
      "geosmithia-argillacea",
      "rasamsonia-argillacea",
      "saprochaete-clavata",
      "magnusiomyces-capitatus",
      "kodamaea-ohmeri",
      "yarrowia-lipolytica",
      "filobasidiella-neoformans",
      "penicillium-marneffei-complex",
      "phaeoacremonium-parasiticum",
      "pyrenochaeta-romeroi",
      "scytalidium-dimidiatum",
      "neoscytalidium-hyalinum",
      "basidiobolus-ranarum",
      "conidiobolus-coronatus",
      "syncephalastrum-racemosum",
      "apophysomyces-elegans",
      "saksenaea-vasiformis",
      "hortaea-werneckii",
      "piedraia-hortae",
      "aureobasidium-pullulans",
      "scopulariopsis-brumptii",
      "paecilomyces-variotii",
      "trichophyton-soudanense",
    ],
  },
  parasites: {
    high: [
      "plasmodium-falciparum",
      "toxoplasma-gondii",
      "giardia-lamblia",
      "entamoeba-histolytica",
      "trypanosoma-cruzi",
      "leishmania-donovani",
      "trichomonas-vaginalis",
      "cryptosporidium-parvum",
      "naegleria-fowleri",
      "ascaris-lumbricoides",
      "enterobius-vermicularis",
      "strongyloides-stercoralis",
      "necator-americanus",
      "schistosoma-mansoni",
      "taenia-solium",
      "echinococcus-granulosus",
      "trichinella-spiralis",
      "wuchereria-bancrofti",
      "onchocerca-volvulus",
      "sarcoptes-scabiei",
      "pediculus-humanus-capitis",
      "ixodes-scapularis",
      "plasmodium-vivax",
      "babesia-microti",
    ],
    medium: [
      "trypanosoma-brucei",
      "leishmania-braziliensis",
      "acanthamoeba-castellanii",
      "cyclospora-cayetanensis",
      "balantidium-coli",
      "ancylostoma-duodenale",
      "toxocara-canis",
      "anisakis-simplex",
      "dracunculus-medinensis",
      "loa-loa",
      "brugia-malayi",
      "trichuris-trichiura",
      "angiostrongylus-cantonensis",
      "clonorchis-sinensis",
      "fasciola-hepatica",
      "paragonimus-westermani",
      "schistosoma-haematobium",
      "schistosoma-japonicum",
      "diphyllobothrium-latum",
      "hymenolepis-nana",
      "demodex-folliculorum",
      "cimex-lectularius",
      "dermatobia-hominis",
      "plasmodium-ovale",
      "plasmodium-malariae",
      "plasmodium-knowlesi",
      "enterocytozoon-bieneusi",
      "balamuthia-mandrillaris",
      "triatoma-infestans",
      "anopheles-gambiae",
      "aedes-aegypti",
      "cystoisospora-belli",
    ],
    demigod: [
      "halicephalobus-gingivalis",
      "thelazia-callipaeda",
      "gongylonema-pulchrum",
      "dioctophyme-renale",
      "syngamus-laryngeus",
      "ternidens-deminutus",
      "raillietina-celebensis",
      "bertiella-studeri",
      "echinococcus-vogeli",
      "echinococcus-oligarthrus",
      "sappinia-pedata",
      "trachipleistophora-hominis",
      "vittaforma-corneae",
      "chilomastix-mesnili",
      "iodamoeba-buetschlii",
      "endolimax-nana",
      "entamoeba-coli",
      "entamoeba-polecki",
      "trypanosoma-rangeli",
      "neospora-caninum",
      "sarcocystis-suihominis",
      "sarcocystis-hominis",
      "androlaelaps-casalis",
      "ornithonyssus-sylviarum",
      "cheyletiella-blakei",
      "oestrus-ovis",
      "cordylobia-anthropophaga",
      "chrysomya-bezziana",
      "liponyssoides-sanguineus",
      "ornithodoros-hermsi",
      "plasmodium-cynomolgi",
      "cyclospora-acidiformis",
      "dracunculus-medinensis-aquatic",
      "oesophagostomum-bifurcum",
      "metagonimus-yokogawai",
      "heterophyes-heterophyes",
      "dicrocoelium-dendriticum",
      "echinostoma-ilocanum",
    ],
  },
  pharmacology: {
    high: [
      "penicillin-g",
      "amoxicillin",
      "vancomycin",
      "ceftriaxone",
      "azithromycin",
      "ciprofloxacin",
      "doxycycline",
      "metronidazole",
      "gentamicin",
      "tmp-smx",
      "rifampin",
      "isoniazid",
      "clindamycin",
      "meropenem",
      "piperacillin-tazobactam",
      "acyclovir",
      "oseltamivir",
      "fluconazole",
      "amphotericin-b",
      "albendazole",
      "ivermectin",
      "praziquantel",
      "chloroquine",
      "lisinopril",
      "metoprolol",
      "amlodipine",
      "atorvastatin",
      "furosemide",
      "hydrochlorothiazide",
      "warfarin",
      "aspirin",
      "metformin",
      "insulin-glargine",
      "albuterol",
      "omeprazole",
      "prednisone",
      "morphine",
      "lorazepam",
      "sertraline",
      "levothyroxine",
      "methotrexate",
      "cisplatin",
      "doxorubicin",
      "epinephrine",
      "atropine",
    ],
    medium: [
      "nafcillin",
      "cefazolin",
      "cefepime",
      "linezolid",
      "daptomycin",
      "levofloxacin",
      "ethambutol",
      "pyrazinamide",
      "valacyclovir",
      "ganciclovir",
      "remdesivir",
      "tenofovir",
      "dolutegravir",
      "sofosbuvir",
      "voriconazole",
      "caspofungin",
      "terbinafine",
      "nystatin",
      "mebendazole",
      "pyrantel-pamoate",
      "primaquine",
      "artemether-lumefantrine",
      "nitazoxanide",
      "pentamidine",
      "losartan",
      "carvedilol",
      "digoxin",
      "amiodarone",
      "spironolactone",
      "clopidogrel",
      "heparin",
      "enoxaparin",
      "simvastatin",
      "nitroglycerin",
      "insulin-lispro",
      "levodopa-carbidopa",
      "haloperidol",
      "fluoxetine",
      "gabapentin",
      "diazepam",
      "ondansetron",
      "montelukast",
      "fluticasone",
      "tiotropium",
      "cyclophosphamide",
      "paclitaxel",
      "vincristine",
      "imatinib",
      "rituximab",
      "tamoxifen",
      "dexamethasone",
      "semaglutide",
      "empagliflozin",
      "propranolol",
      "lithium",
      "phenytoin",
      "naloxone",
      "succinylcholine",
    ],
    demigod: [
      "iclaprim",
      "novobiocin",
      "optochin",
      "sparfloxacin",
      "trovafloxacin",
      "carbarsone",
      "bithionol",
      "metrifonate",
      "tafenoquine-prophylaxis",
      "tafenoquine-combo",
      "obeldesivir",
      "ozonide-oz439",
      "fosmanogepix",
      "manogepix",
      "olorofim",
      "tavaborole",
      "fexinidazole",
      "suramin",
      "melarsoprol",
      "eflornithine",
      "oxamniquine",
      "diloxanide-furoate",
      "fumagillin",
      "lefamulin",
      "omadacycline",
      "eravacycline",
      "plazomicin",
      "cefiderocol",
      "sulbactam-durlobactam",
      "pretomanid",
      "delamanid",
      "ethionamide",
      "cycloserine",
      "spectinomycin",
      "methenamine",
      "maribavir",
      "lenacapavir",
      "fostemsavir",
      "ibalizumab",
      "brincidofovir",
      "adefovir",
      "delavirdine",
      "idoxuridine",
      "vidarabine",
      "trifluridine",
      "amorolfine",
      "butenafine",
      "tedizolid",
      "telavancin",
      "oritavancin",
      "quinupristin-dalfopristin",
      "fusidic-acid",
      "rezafungin",
      "ibrexafungerp",
      "tolvaptan",
      "conivaptan",
      "ranolazine",
      "ivabradine",
      "dofetilide",
      "mexiletine",
      "cilostazol",
      "pralidoxime",
      "physostigmine",
      "edrophonium",
      "carbachol",
      "cevimeline",
      "reserpine",
      "yohimbine",
      "riluzole",
      "pirfenidone",
      "dornase-alfa",
      "ivacaftor",
      "bosentan",
      "lubiprostone",
      "linaclotide",
      "prucalopride",
      "methylnaltrexone",
      "pramlintide",
      "cinacalcet",
      "teriparatide",
      "fludrocortisone",
    ],
  },
};

const cache = new Map<string, Tier>();

export function tierFor(section: string, slug: string): Tier {
  const key = `${section}:${slug}`;
  const cached = cache.get(key);
  if (cached) return cached;
  const set = TIERS[section];
  let tier: Tier = "Good to know";
  if (set) {
    if (set.high.includes(slug)) tier = "High yield";
    else if (set.medium.includes(slug)) tier = "Medium yield";
    else if (set.demigod.includes(slug)) tier = "Demigod";
  }
  cache.set(key, tier);
  return tier;
}
